// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV3jNiZHhZk-0NaL-Ruv8w3B3w5PYYe1Y',
    appId: '1:334753958072:web:f32af948578d77f1004c4d',
    messagingSenderId: '334753958072',
    projectId: 'maduromobile',
    authDomain: 'maduromobile.firebaseapp.com',
    storageBucket: 'maduromobile.firebasestorage.app',
    measurementId: 'G-6LL9XSQC46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3B28j0KxdwMqW4Pr2OtAHfB9dYicjODI',
    appId: '1:334753958072:android:2a5d0295c61008b2004c4d',
    messagingSenderId: '334753958072',
    projectId: 'maduromobile',
    storageBucket: 'maduromobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKFKewlQD8JULagnJudiO85VIZXWagq-E',
    appId: '1:334753958072:ios:f9f6e26b3369ba14004c4d',
    messagingSenderId: '334753958072',
    projectId: 'maduromobile',
    storageBucket: 'maduromobile.firebasestorage.app',
    iosBundleId: 'com.example.maduro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKFKewlQD8JULagnJudiO85VIZXWagq-E',
    appId: '1:334753958072:ios:f9f6e26b3369ba14004c4d',
    messagingSenderId: '334753958072',
    projectId: 'maduromobile',
    storageBucket: 'maduromobile.firebasestorage.app',
    iosBundleId: 'com.example.maduro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV3jNiZHhZk-0NaL-Ruv8w3B3w5PYYe1Y',
    appId: '1:334753958072:web:280f78e297b3905d004c4d',
    messagingSenderId: '334753958072',
    projectId: 'maduromobile',
    authDomain: 'maduromobile.firebaseapp.com',
    storageBucket: 'maduromobile.firebasestorage.app',
    measurementId: 'G-SB8HRFPS03',
  );
}
